# Use the official Python image from the Docker Hub
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt /app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Install libGL Some error during cloud run due to missing import
RUN apt-get update && \
    apt-get install -y libgl1-mesa-glx && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
    
# Copy the current directory contents into the container at /app
COPY . /app

# Expose the port that the Flask app will run on
EXPOSE 8080

# Set environment variable for Flask app
ENV FLASK_APP=run.py
ENV PORT=8080

# Run the Flask app with Waitress
CMD ["waitress-serve", "--host=0.0.0.0", "--port=8080", "run:app"]